apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: backend-deployment
  name: backend-deployment
  namespace: flashbacker-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend-deployment
  template:
    metadata:
      labels:
        run: backend-deployment
    spec:
      containers:
      - image: registry.gitlab.com/flashbacker/backend:master-6082785e
        name: backend-deployment
        ports:
        - containerPort: 8081
        envFrom:
          - secretRef:
              name: dynamodb-secret
          - configMapRef:
              name: jwk-set-uri-configmap
        readinessProbe:
          httpGet:
            port: 8081
            path: /
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: regcred
