apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: frontend-deployment
  name: frontend-deployment
  namespace: flashbacker-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: frontend-deployment
  template:
    metadata:
      labels:
        run: frontend-deployment
    spec:
      containers:
      - image: registry.gitlab.com/flashbacker/frontend:master-05194f32
        name: frontend-deployment
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: cognito-secret
          - configMapRef:
              name: backend-url-configmap
        readinessProbe:
          httpGet:
            port: 80
            path: /
      imagePullSecrets:
      - name: regcred
